### ISSUE TITLE
Returns empty emoji even if there is no emoji present.

### ISSUE THREAD

**Issue by gwilakers** [clonn/slack-node-sdk#13]
I am not sure if this is working as intended, but currently when issuing a webhook, the request sent to slack by default has an empty emoji included even if there was no emoji field specified.

**Comment by clonn** [comment]
@gwilakers  should be ok, i put `undefined` and `""` empty string to webhook function, that work well.
could you give me some example code and error message ?

**Comment by clonn** [comment]
should be work well.
