### ISSUE TITLE
Bad request error handling in webhook

### ISSUE THREAD

**Issue by dbellavista** [clonn/slack-node-sdk#14]
When request raises an error, the second and third parameter of the callback are not necessarily defined. So line:
https://github.com/clonn/slack-node-sdk/blob/master/lib/lib/slack.seed.js#L58
throws an `TypeError: Cannot read property 'statusCode' of undefined` upon request error.

**Comment by clonn** [comment]
@dbellavista  already upgrade https://www.npmjs.com/package/slack-node version, please update and try again.
