### ISSUE TITLE
package.json repository field

### ISSUE THREAD

**Issue by sabrehagen** [clonn/slack-node-sdk#15]
Hi,

You're missing a repository field in your package.json file, and npm complains that it doesn't exist when installing. Could you add the following so there aren't any issues? Thanks!
```
"repository": {
    "type": "git",
    "url": "https://github.com/clonn/slack-node-sdk/"
  },
```
Also, if you could link your github repository to the npm page it would really help :)

**Comment by clonn** [comment]
https://github.com/clonn/slack-node-sdk/commit/0b7059ee0b22a067fb1506344285c2e270966336

@sabrehagen thanks for mention it, already fixed.
