### ISSUE TITLE
Crash in Slack.api when the response contains invalid JSON 

### ISSUE THREAD

**Issue by avuori** [clonn/slack-node-sdk#20]
Probably desired instead of crashing: should call the callback with an error.

Relevant stack:
SyntaxError: Unexpected token <
  at Object.parse (native)
  at Request.<anonymous> (/.../node_modules/slack-node/lib/lib/slack.seed.js:110:28)

(happens with version 0.1.3)

**Comment by kevinburkeshyp** [comment]
Fixed in https://github.com/clonn/slack-node-sdk/pull/21
