### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by kevinburkeshyp** [clonn/slack-node-sdk#23]
Can you tag releases of the library so it's clear which commits line up with which NPM versions? FWIW `npm version minor` | `npm version patch` will automatically do this for you.

Did you do a new release with the change merged last night?

**Comment by kevinburkeshyp** [comment]
hey @clonn - not sure how much time you have for this lib, but if you add me as a maintainer I can keep pushing tags & versions and stuff

**Comment by clonn** [comment]
@kevinburkeshyp  hey, thanks for your help, already added as maintainer.
