### ISSUE TITLE
offer support for icon_url

### ISSUE THREAD

**Issue by olivierlesnicki** [clonn/slack-node-sdk#24]
it's not trivial that one must use icon_emoji

**Comment by kevinburkeshyp** [comment]
If I am reading the code correctly, if you pass a URL to `icon_emoji` it'll set `icon_url` on the request? see here: https://github.com/clonn/slack-node-sdk/blob/master/src/lib/slack.seed.coffee#L20

**Comment by olivierlesnicki** [comment]
Yes and it does work. However, as stated in my initial message, this is not trivial.
SLACK official API supports icon_url, therefore I'm expecting to be able to pass icon_url

**Comment by kevinburkeshyp** [comment]
it seems a little funky but also seems like there's a workaround - if you want to submit a PR, I'll merge
