### ISSUE TITLE
does not use configured botname or icon when using Slack Realtime API

### ISSUE THREAD

**Issue by ghostsquad** [clonn/slack-node-sdk#26]
I have a bot named `test` with a specific icon. When I run the example code, I got a message from `bot` and a generic slack icon.

**Comment by nuledgm** [comment]
I also get this. Any fix available?

**Comment by kevinburkeshyp** [comment]
which example code are you using? here are the parameters you should send: https://api.slack.com/methods/chat.postMessage (see `icon_url` maybe ? )

if you're using the API I believe options are just passed through

**Comment by altaurog** [comment]
I know this is an old thread, but the solution @ghostsquad is to include `as_user: true` in your POST parameters: https://api.slack.com/methods/chat.postMessage#authorship
