### ISSUE TITLE
Incorrect errors

### ISSUE THREAD

**Issue by danilvalov** [clonn/slack-node-sdk#35]
Hi.
I use this example:
```
var Slack = require('slack-node');
apiToken = "-- api token --";

slack = new Slack(apiToken);

slack.api("users.list", function(err, response) {
  console.log(response);
});

slack.api('chat.postMessage', {
  text:'hello from nodejs',
  channel:'#general'
}, function(err, response){
  console.log(response);
});
```

and it returns:

**Error:**
```
null
```
**Response:**
```
{ ok: false, error: 'invalid_auth' }
```

but it should return:

**Error:**
```
invalid_auth
```
**Response:**
```
null
```

Please, fix it.

**Comment by kevinburkeshyp** [comment]
Hi, I believe this response is sent back straight from the Slack API, so I'm not sure what we should do about it. Currently the `err` channel is used for request errors (timeouts, ECONNRESET, etc) and for JSON parsing errors, if the Slack API returns a response, we just return it through.

> Please, fix it.

We're all volunteers here. You wouldn't speak to me like that in person, so please don't do it here.

**Comment by clonn** [comment]
@danilvalov in your local env for run test code, please find slack token to replace `-- api token --`, we promise the result is correct and wonderful.
