### ISSUE TITLE
Elaborate on __uri____ in readme

### ISSUE THREAD

**Issue by dawsonbotsford** [clonn/slack-node-sdk#38]
In the primary readme a line of the JavaScript contains this: 

```js
webhookUri = "__uri___";
```

But how do we get said uri? Is this the plain url of the clack channel? Do we get this from one of the Slack account options page?

**Comment by clonn** [comment]
@dawsonbotsford 
when you create web application from slack, there is a webhook uri.

![image](https://cloud.githubusercontent.com/assets/347807/14402358/ded12872-fe65-11e5-8dfd-b86b1e55aca1.png)

that is easy to find 
[https://api.slack.com/incoming-webhooks](https://api.slack.com/incoming-webhooks)

**Comment by dawsonbotsford** [comment]
Why not add this to the readme? If it's simple to explain and helps users get started, adding that to the readme would help ease the process of getting up to speed.
