### ISSUE TITLE
Does this tool support promises

### ISSUE THREAD

**Issue by hisabimbola** [clonn/slack-node-sdk#42]
Hello, 

I am planning to use this module and I saw from the readme that it supports promises, but when I do this I get an error that `.then` is not a function

```js
slack.api('users.list').then((result) => {
})
````

Any help would be highly appreciated.

Danke.

**Comment by kevinburkeshyp** [comment]
I don't think so... sorry...

**Comment by hisabimbola** [comment]
Any plans to add it @kevinburkeshyp I can submit a PR is it's a desired feature?

**Comment by Thebigbignooby** [comment]
+1
README states : 
```
0.1.6

support ES6, promise function.
```
however it throws a TypeError callback is not a function when I try to use it as a promise

**Comment by kevinburke** [comment]
Hi folks, really sorry about this. I think I am going to leave the library as is for the moment. I'd encourage you to wrap it via `Promise.promisify()` in your own codebase, or just check the source code into your own codebase, and modify it to fit your needs. 

I'll update the README so it doesn't mention promises anymore.
