### ISSUE TITLE
Now getting "undefined is not a function"

### ISSUE THREAD

**Issue by thelinuxlich** [clonn/slack-node-sdk#9]
I'm using the API exactly like the example but something has been updated and it's not working anymore.

**Comment by clonn** [comment]
@thelinuxlich  could you give me your code or paste error message for me. thanks

**Comment by clonn** [comment]
there are some typo readme, already fixed it. @thelinuxlich please run again.

or you can run https://github.com/clonn/slack-node-sdk/tree/master/example , tell me result then.

thanks

**Comment by thelinuxlich** [comment]
worked!
